### ISSUE TITLE
about the subscribe api implementation

### ISSUE THREAD

**Issue by ChengOrangeJu** [NaixSpirit/neb.rb#1]
The subscribe api is an keep-alive connection, and the subscribed events is downloaded as stream, hence a callback function should be provided to handle the events, such as onDownloadProcess in neb.js and HttpClientListener in neb.java, or $onDownloadProgress in neb.php

You could refer to the subscribe api implemented in other languages, although they are not handled very elegantly. I think you can make it better!

using subscribe api in neb.java

 nebulasClient.subscribe(new SubscribeRequest("chain.linkBlock", "chain.pendingTransaction"), new HttpClientListener<Event>() {
            @Override
            public void onMessage(Response<Event> event) {
                System.out.println(event.getResult().getTopic());
                System.out.println(event.getResult().getData());
            }
        });
using subscribe api in neb.js

var api = new Neb().api;
var topics = ["chain.linkBlock", "chain.pendingTransaction"]
var onDownloadProces = function (event) {
  console.log(event)
}
api.subscribe(topics , onDownloadProces)
using subscribe api in neb.php

$topics = ["chain.linkBlock", "chain.pendingTransaction","chain.newTailBlock"];
/**
 * Explanation of eventCallback function:
 * It is the function that handle the subscribed data,
 * Actually it is the "CURLOPT_WRITEFUNCTION" option for curl, please refer @link http://php.net/manual/en/function.curl-setopt.php *
 */
function eventCallback($curlHandle, $data){
    echo "received data: $data",PHP_EOL; //handle the subscribed event data
    return strlen($data);   //return the received data length, or the http connection will close.
}

$neb->api->subscribe($topics, "eventCallback");

**Comment by xuanyu-h** [comment]
in neb.rb

```ruby
client.api.subscribe(
  topics: ["chain.pendingTransaction"],
  on_download_progress: ->(c) { puts c }
)
```
