### ISSUE TITLE
'call' seem doesn't work

### ISSUE THREAD

**Issue by 1c7** [NaixSpirit/neb.rb#7]
## What I am trying to do: call Smart Contract on Nebulas
Contract Address: [n1f4tzQJjoQaUQzDmf7uXP8SC2LTzYYjvAE](https://explorer.nebulas.io/#/testnet/address/n1f4tzQJjoQaUQzDmf7uXP8SC2LTzYYjvAE)

## And I found `call` in neb.rb
https://github.com/NaixSpirit/neb.rb/blob/a0d1a4dc54e52d65bd195c556395584d24cbee56/lib/neb/client/api.rb#L30-L42

## Usage
```ruby
    client = Neb::Client.new
    resp = client.api.call(
      from: account.address, 
      to: 'n1f4tzQJjoQaUQzDmf7uXP8SC2LTzYYjvAE',
      value: 0,
      nonce: account_state[:nonce].to_i + 1,
      gas_price: 1000000,
      gas_limit: 2000000,
      contract: contract.to_json,
    )
```
seem doesn't work.

## So I use following, (send request myself)
```ruby
    testnet = 'https://testnet.nebulas.io'
    query_address = 'n1XL3BsqPiGMFkL9tAxnKziRyQ1L57kDWRz'
    response = RestClient.post("#{testnet}/v1/user/call",{
        "from": "n1XL3BsqPiGMFkL9tAxnKziRyQ1L57kDWRz", # 用测试网钱包
        "to": "n1f4tzQJjoQaUQzDmf7uXP8SC2LTzYYjvAE",   # 合约地址
        "value": "0",
        "nonce": 20,
        "gasPrice": "1000000",
        "gasLimit": "200000", 
        "contract": {
          "function" => "balanceOf",
          "args" => "[\"#{query_address}\"]"
        }
      }.to_json
    )

    render json: response.body
```

not sure what's going on for now, I am opening this issue to just let you know.

**Comment by xuanyu-h** [comment]
Did you configure Neb first?
```ruby
Neb.configure(host: 'https://testnet.nebulas.io')
```

**Comment by 1c7** [comment]
@NaixSpirit  Thanks for reply.
and Yes I did configure
```
   Neb.configure(host: 'https://testnet.nebulas.io')
```

now I am switching my focus to some other work, not Nebulas anymore,
I may come back on this after few day or few week, if this `call` methods doesn't work happen again,
I would let you know~

let me close this issue for now

Thanks again for reply
